/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a07d674f-22f8-44dd-8ba5-d51d5a068603",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xCUSY8VOs",
    "aws_user_pools_web_client_id": "748k04qbrjo4muaffajsefqonp",
    "oauth": {
        "domain": "hexalauthdomain.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
